data_ingestion:
  test_size: 0.2
  random_state: 42

data_transformation:
  numerical_columns: ["writing_score", "reading_score"]
  categorical_columns: ["gender", "race_ethnicity", "parental_level_of_education", 
                       "lunch", "test_preparation_course"]
  target_column: "math_score"

model_training:
  models:
    random_forest:
      n_estimators: 100
      max_depth: 10
      random_state: 42
    gradient_boosting:
      n_estimators: 100
      learning_rate: 0.1
      random_state: 42
    linear_regression:
      fit_intercept: true

